#!/bin/sh

echo
echo "Rweezy userspace started."
echo

if ip link show eth0 >/dev/null 2>&1; then
    echo "Starting network..."
    ip link set eth0 up
    udhcpc -i eth0
fi

echo
echo "Network initialized."
echo
uname -a
cat /proc/rweezy
echo
echo "Starting Rweezy shell..."
echo

exec setsid cttyhack /bin/sh
